[profile.default]
gas_reports = ["*"]
solc_version = '0.8.16'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[etherscan]
mainnet = { key="${ETHERSCAN_API_KEY}", chainId=1 }
goerli = { key="${ETHERSCAN_API_KEY}", chainId=5 }
optimism = { key="${OPTIMISM_SCAN_API_KEY}", chainId=10 }
arbitrum = { key="${ARBITRUM_SCAN_API_KEY}", chainId=42161 }
polygon = { key="${POLYGON_SCAN_API_KEY}", chainId=137 }
gnosis = { key="${GNOSIS_SCAN_API_KEY}", chainId=100 }
fantom = { key="${FANTOM_SCAN_API_KEY}", chainId=250 }